## 7. np.full()

In [2]:
import numpy as np

In [3]:
a1=np.full((2,2),11)
a1

array([[11, 11],
       [11, 11]])

In [4]:
a1=np.full(4,"A",dtype=str)
a1

array(['A', 'A', 'A', 'A'], dtype='<U1')

## 8. np.eye() / np.identity()

In [5]:
a1=np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 9. np.diag()

In [6]:
a1=np.diag([1,2,3])
print(a1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Array Manipulation

In [ ]:
-> functions to modify array shape, size ,structure and content

## 2.1 reshape()

In [ ]:
-> change array dimensions without altering data

In [11]:
a1=np.arange(12)
print(a1)
a1.size
reshaped1=a1.reshape(4,3)
print(reshaped1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## 2.2 resize()

In [ ]:
-> change array size (repeats elements if new size is larger)

In [14]:
a1=np.array([1,2,3])
print(a1)
a2=np.resize(a1,(3,2))
print(a2)

[1 2 3]
[[1 2]
 [3 1]
 [2 3]]


## 2.3 flatten()

In [ ]:
-> to convert N-dimensional arrays to 1-D
-> flatten(): returns a copy

In [16]:
a1=np.array([[1,2],[3,4]])
print(a1)
flat=a1.flatten()
print(flat)

[[1 2]
 [3 4]]
[1 2 3 4]


## 2.4 transpose()

In [ ]:
-> reverse or permute array axes
-> arr.transpose() or arr.T

In [17]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
transposed=a1.transpose()
print(transposed)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 2.5 concatenate()

In [ ]:
-> joins arrays along an existing axis

In [19]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
concat=np.concatenate((a1,a2),axis=0)
print(concat)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 2.6 append()

In [ ]:
-> add values to the end of an array

In [20]:
a1=np.array([1,2,3])
new_a1=np.append(a1,[4,5])
print(new_a1)

[1 2 3 4 5]


## 2.7 insert()

In [ ]:
-> insert values at a specific position

In [22]:
a1=np.array([1,2,4])
new_a1=np.insert(a1,2,3)  # inserts 3 at index no '2'
print(new_a1)

[1 2 3 4]


## 2.8 delete()

In [ ]:
-> remove elements along an axis

In [24]:
a1=np.array([1,2,3,4])
new_a1=np.delete(a1,3)
print(new_a1)

[1 2 3]


## 2.9 sort()

In [ ]:
-> sort array elements

In [25]:
a1=np.array([2,54,5,0])
sorted_a1=np.sort(a1)
print(sorted_a1)

[ 0  2  5 54]


## Mathematical Operations

## 3.1 np.sum()

In [27]:
a1_sum=np.sum(a1)
print(a1_sum)

61


## 3.2 np.mean()

In [28]:
a1_avg=np.mean(a1)
print(a1_avg)

15.25


## 3.3 np.max() & np.min()

In [29]:
a1_max=np.max(a1)
print(a1_max)
a1_min=np.min(a1)
print(a1_min)

54
0


## 3.4 np.std() & np.var()

In [31]:
print(np.std(a1))
print(np.var(a1))

22.442983313276336
503.6875


## 3.5 np.sqrt() & np.power()

In [33]:
print(np.sqrt(a1))
print(np.power(a1,2))

[1.41421356 7.34846923 2.23606798 0.        ]
[   4 2916   25    0]


## 3.6 np.dot()

In [34]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.dot(a1,a2))

32


## 3.7 np.add(), np.subtract(),np.multiply(),np.divide()

In [36]:
a=np.array([1,2])
b=np.array([3,4])
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(b,a))

[4 6]
[2 2]
[3 8]
[3. 2.]


## 3.8 np,round()

In [39]:
a1=np.array([1.2,3.4,5.6])
print(np.round(a1))

[1. 3. 6.]


## Logical & Indexing

In [ ]:
-> returns indices or values based on a condition
-> returns indices where condition is True

In [40]:
a1=np.array([1,4,2,5,8])
result=np.where(a1>5)
print(result)  # we will get index numbers

(array([4]),)


In [ ]:
-> to check if any element satisfies a condition, we use np.any()

In [42]:
a1=np.array([1,2,3,45,6])
print(np.any(a1>0))

True


## np.unique()

In [44]:
a1=np.array([1,3,4,5,3,2])
print(np.unique(a1))

[1 2 3 4 5]
