## Numpy

In [ ]:
-> numpy is considered for high level data
-> numpy array is a collection of homogeneous datatypes
-> numpy is faster than list
-> 

In [3]:
import numpy as np
import pandas as pd

In [4]:
import numpy as np

## How to create numpy array

In [5]:
array1=np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [6]:
type(array1)

numpy.ndarray

In [7]:
array1.dtype

dtype('int64')

## various functions to create arrays

## zeros()

In [8]:
a11=np.zeros((2,2))
a11    # creates array with all zeroes

array([[0., 0.],
       [0., 0.]])

In [10]:
a22=np.zeros((3,2))
a22

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## ones()

In [11]:
one1=np.ones((2,2))
one1   # creates array with ones

array([[1., 1.],
       [1., 1.]])

## np.arange()

In [12]:
a1=np.arange(10,20)
a1  # creates array of given range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## np.linspace()

In [14]:
s1=np.linspace(10,20,12)
s1

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

## np.random.rand()

In [15]:
a1=np.random.rand(2,3)
a1 # creates array of random numbers between 0 and 1

array([[0.7627002 , 0.24778378, 0.64317598],
       [0.58548581, 0.68033059, 0.53949573]])

## np.random.randint()

In [18]:
a11=np.random.randint(10,100,(3,3))
a11

array([[93, 36, 61],
       [20, 63, 41],
       [40, 37, 27]], dtype=int32)

## Typecasting in Numpy Array

In [19]:
import numpy as np

In [20]:
array1=np.array([1,2,3,4,5])
array1.dtype

dtype('int64')

In [21]:
array1=np.array([1,2,3,4],dtype=float)
array1

array([1., 2., 3., 4.])

In [22]:
array1=np.array([1,2,3,4],dtype=str)
array1

array(['1', '2', '3', '4'], dtype='<U1')

## Dimensions in numpy array

## 1. 0-D array

In [23]:
z1=np.array(30)
z1.ndim

0

## 2. 1-D array

In [25]:
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
a1.ndim

[1 2 3 4 5 6 7 8]


1

## 3. 2-D array

In [27]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
a1.ndim

[[1 2 3]
 [4 5 6]]


2

## 4. 3-D array

In [29]:
a1=np.array([[[1,2,3],[4,5,6]]])
print(a1)
a1.ndim

[[[1 2 3]
  [4 5 6]]]


3

## Indexing and Slicing

In [30]:
a1=np.array([1,2,3,4,5,6,7,8])
a1[0]

np.int64(1)

In [31]:
a1[-1]

np.int64(8)

In [32]:
a1[1::2]

array([2, 4, 6, 8])

In [34]:
a1[1:8:3]

array([2, 5, 8])

In [35]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1)
print(a1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [36]:
a1[0][1:]

array([2, 3, 4])